// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "./parser.fsy"


# 9 "parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | RPAREN
  | LPAREN
  | UMINUS
  | DIVIDE
  | TIMES
  | MINUS
  | PLUS
  | NUMERAL of (int)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_RPAREN
    | TOKEN_LPAREN
    | TOKEN_UMINUS
    | TOKEN_DIVIDE
    | TOKEN_TIMES
    | TOKEN_MINUS
    | TOKEN_PLUS
    | TOKEN_NUMERAL
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__starttoplevel
    | NONTERM_toplevel
    | NONTERM_expression

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | RPAREN  -> 1 
  | LPAREN  -> 2 
  | UMINUS  -> 3 
  | DIVIDE  -> 4 
  | TIMES  -> 5 
  | MINUS  -> 6 
  | PLUS  -> 7 
  | NUMERAL _ -> 8 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_RPAREN 
  | 2 -> TOKEN_LPAREN 
  | 3 -> TOKEN_UMINUS 
  | 4 -> TOKEN_DIVIDE 
  | 5 -> TOKEN_TIMES 
  | 6 -> TOKEN_MINUS 
  | 7 -> TOKEN_PLUS 
  | 8 -> TOKEN_NUMERAL 
  | 11 -> TOKEN_end_of_input
  | 9 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__starttoplevel 
    | 1 -> NONTERM_toplevel 
    | 2 -> NONTERM_expression 
    | 3 -> NONTERM_expression 
    | 4 -> NONTERM_expression 
    | 5 -> NONTERM_expression 
    | 6 -> NONTERM_expression 
    | 7 -> NONTERM_expression 
    | 8 -> NONTERM_expression 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 11 
let _fsyacc_tagOfErrorTerminal = 9

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | RPAREN  -> "RPAREN" 
  | LPAREN  -> "LPAREN" 
  | UMINUS  -> "UMINUS" 
  | DIVIDE  -> "DIVIDE" 
  | TIMES  -> "TIMES" 
  | MINUS  -> "MINUS" 
  | PLUS  -> "PLUS" 
  | NUMERAL _ -> "NUMERAL" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | RPAREN  -> (null : System.Object) 
  | LPAREN  -> (null : System.Object) 
  | UMINUS  -> (null : System.Object) 
  | DIVIDE  -> (null : System.Object) 
  | TIMES  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | NUMERAL _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 7us; 65535us; 0us; 2us; 11us; 5us; 12us; 6us; 13us; 7us; 14us; 8us; 15us; 9us; 16us; 10us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 5us; 1us; 3us; 4us; 5us; 6us; 1us; 1us; 1us; 2us; 5us; 3us; 3us; 4us; 5us; 6us; 5us; 3us; 4us; 4us; 5us; 6us; 5us; 3us; 4us; 5us; 5us; 6us; 5us; 3us; 4us; 5us; 6us; 6us; 5us; 3us; 4us; 5us; 6us; 7us; 5us; 3us; 4us; 5us; 6us; 8us; 1us; 3us; 1us; 4us; 1us; 5us; 1us; 6us; 1us; 7us; 1us; 8us; 1us; 8us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 10us; 12us; 14us; 20us; 26us; 32us; 38us; 44us; 50us; 52us; 54us; 56us; 58us; 60us; 62us; |]
let _fsyacc_action_rows = 18
let _fsyacc_actionTableElements = [|3us; 32768us; 2us; 16us; 6us; 15us; 8us; 4us; 0us; 49152us; 5us; 32768us; 0us; 3us; 4us; 14us; 5us; 11us; 6us; 13us; 7us; 12us; 0us; 16385us; 0us; 16386us; 0us; 16387us; 2us; 16388us; 4us; 14us; 5us; 11us; 2us; 16389us; 4us; 14us; 5us; 11us; 0us; 16390us; 0us; 16391us; 5us; 32768us; 1us; 17us; 4us; 14us; 5us; 11us; 6us; 13us; 7us; 12us; 3us; 32768us; 2us; 16us; 6us; 15us; 8us; 4us; 3us; 32768us; 2us; 16us; 6us; 15us; 8us; 4us; 3us; 32768us; 2us; 16us; 6us; 15us; 8us; 4us; 3us; 32768us; 2us; 16us; 6us; 15us; 8us; 4us; 3us; 32768us; 2us; 16us; 6us; 15us; 8us; 4us; 3us; 32768us; 2us; 16us; 6us; 15us; 8us; 4us; 0us; 16392us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 4us; 5us; 11us; 12us; 13us; 14us; 17us; 20us; 21us; 22us; 28us; 32us; 36us; 40us; 44us; 48us; 52us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 1us; 3us; 3us; 3us; 3us; 2us; 3us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 16386us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16392us; |]
let _fsyacc_reductions ()  =    [| 
# 122 "parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> Syntax.expression in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : 'gentype__starttoplevel));
# 131 "parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expression in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "./parser.fsy"
                                          _1 
                   )
# 29 "./parser.fsy"
                 : Syntax.expression));
# 142 "parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> int in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "./parser.fsy"
                                                               Syntax.Numeral _1 
                   )
# 33 "./parser.fsy"
                 : 'gentype_expression));
# 153 "parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expression in
            let _3 = parseState.GetInput(3) :?> 'gentype_expression in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "./parser.fsy"
                                                        Syntax.Times (_1, _3) 
                   )
# 34 "./parser.fsy"
                 : 'gentype_expression));
# 165 "parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expression in
            let _3 = parseState.GetInput(3) :?> 'gentype_expression in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "./parser.fsy"
                                                       Syntax.Plus (_1, _3) 
                   )
# 35 "./parser.fsy"
                 : 'gentype_expression));
# 177 "parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expression in
            let _3 = parseState.GetInput(3) :?> 'gentype_expression in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "./parser.fsy"
                                                        Syntax.Minus (_1, _3) 
                   )
# 36 "./parser.fsy"
                 : 'gentype_expression));
# 189 "parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expression in
            let _3 = parseState.GetInput(3) :?> 'gentype_expression in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "./parser.fsy"
                                                         Syntax.Divide (_1, _3) 
                   )
# 37 "./parser.fsy"
                 : 'gentype_expression));
# 201 "parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_expression in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "./parser.fsy"
                                                               Syntax.Negate _2 
                   )
# 38 "./parser.fsy"
                 : 'gentype_expression));
# 212 "parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_expression in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "./parser.fsy"
                                                               _2 
                   )
# 39 "./parser.fsy"
                 : 'gentype_expression));
|]
# 224 "parser.fs"
let tables : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 12;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = tables.Interpret(lexer, lexbuf, startState)
let toplevel lexer lexbuf : Syntax.expression =
    engine lexer lexbuf 0 :?> _
